### ISSUE TITLE
Hey thanks for the tool :) couple of questions if I may.

### ISSUE THREAD

**Issue by mannp** [oddlama/kanidm-provision#2]
Hi @oddlama 

1) I wondered if the tool can be used standalone rather than as part of your kanidm module?

2) How do we provision KANIDM_PROVISION_IDM_ADMIN_TOKEN, which type of token is it?

3) Is it possible to export some basic config from kanidm to create the initial state.json?

I ask as I tried and failed to use the tool and wanted to get kanidm up and running, so configured it and added a couple of oidc clients. Now I'd like to see how that config looks as a state.json.

Cheers

**Comment by oddlama** [comment]
A1) Sure, this tool is a standalone tool doesn't need anything NixOS specific to work. If you want to use oidc secret provisioning or account password provisioning you just need to make sure that your kanidm is built with the required patches.

A2) It's just the password for the idm_admin account which the tools needs to login. You probably initally got that from `kanidmd recover-account`

A3) That's not possible unfortunately. The tool is designed to not _ever_ touch anything that hasn't been previously provisioned by the tool and the data direction is always from `state.json` into kanidm. If you need an example state.json, I have attached one of generated by the nixos tests below
<details>
<summary>Example state.json</summary>

```json
{
  "groups": {
    "service1-access": {
      "members": [
        "testuser1"
      ],
      "present": true
    },
    "service1-admin": {
      "members": [
        "testuser2"
      ],
      "present": true
    },
    "supergroup1": {
      "members": [
        "testgroup1"
      ],
      "present": true
    },
    "testgroup1": {
      "members": [
        "testuser1"
      ],
      "present": true
    }
  },
  "persons": {
    "testuser1": {
      "displayName": "Test User",
      "groups": [
        "testgroup1",
        "service1-access"
      ],
      "legalName": "Jane Doe",
      "mailAddresses": [
        "jane.doe@example.com"
      ],
      "present": true
    },
    "testuser2": {
      "displayName": "Powerful Test User",
      "groups": [
        "service1-admin"
      ],
      "legalName": "Ryouiki Tenkai",
      "mailAddresses": [],
      "present": true
    }
  },
  "systems": {
    "oauth2": {
      "service1": {
        "allowInsecureClientDisablePkce": false,
        "basicSecretFile": "/nix/store/j8rnv2aihvd89bwnk74karfd78ngx1id-bs-service1",
        "claimMaps": {
          "groups": {
            "joinType": "array",
            "valuesByGroup": {
              "service1-admin": [
                "admin"
              ]
            }
          }
        },
        "displayName": "Service One",
        "originLanding": "https://one.example.com/landing",
        "originUrl": "https://one.example.com/",
        "preferShortUsername": false,
        "present": true,
        "removeOrphanedClaimMaps": true,
        "scopeMaps": {
          "service1-access": [
            "openid",
            "email",
            "profile"
          ]
        },
        "supplementaryScopeMaps": {
          "service1-admin": [
            "admin"
          ]
        }
      },
      "service2": {
        "allowInsecureClientDisablePkce": true,
        "basicSecretFile": null,
        "claimMaps": {},
        "displayName": "Service Two",
        "originLanding": "https://landing2.example.com/",
        "originUrl": "https://two.example.com/",
        "preferShortUsername": true,
        "present": true,
        "removeOrphanedClaimMaps": true,
        "scopeMaps": {},
        "supplementaryScopeMaps": {}
      }
    }
  }
}
```

</details>

**Comment by mannp** [comment]
> A1) Sure, this tool is a standalone tool doesn't need anything NixOS specific to work. If you want to use oidc secret provisioning or account password provisioning you just need to make sure that your kanidm is built with the required patches.

I see, so without the kanidm patches the OIDC accounts get created, but we'd need to pull the secret from kanidm and save that in our secret in nix?
 
> 
> A2) It's just the password for the idm_admin account which the tools needs to login. You probably initally got that from `kanidmd recover-account`

Oops, I see, thought I needed to create a token using that account :)

> 
> A3) That's not possible unfortunately. The tool is designed to not _ever_ touch anything that hasn't been previously provisioned by the tool and the data direction is always from `state.json` into kanidm. If you need an example state.json, I have attached one of generated by the nixos tests below
> Example state.json

Thanks, I have seen the example given, but was trying to populate the data in the state as I have it now, maybe with existing API calls.... I will have to investigate further before wiping out my existing config :)

**Comment by oddlama** [comment]
> > A1) Sure, this tool is a standalone tool doesn't need anything NixOS specific to work. If you want to use oidc secret provisioning or account password provisioning you just need to make sure that your kanidm is built with the required patches.
> 
> I see, so without the kanidm patches the OIDC accounts get created, but we'd need to pull the secret from kanidm and save that in our secret in nix?

Yes, exactly :)
