### ISSUE TITLE
Kanidm, netbird, groups sync and your tool.

### ISSUE THREAD

**Issue by mannp** [oddlama/kanidm-provision#6]
Hi there

Not sure if this is a kanidm restriction but within netbird I am using 'groups' as the sync item with the JWT claim, but every group within kanidm is being transferred to netbird,

I am trying to get the following, a small subset of groups, just for netbird and am not sure if its currently possible with your tool or even kanidm;

```
    "groups": {
        "general_group1": {
            "members": [
                "user1"
            ],
            "present": true
        }
    }
    "netbird_groups": {
        "group1": {
            "members": [
                "user1"
            ],
            "present": true
        }
    }
```

Thanks in advance for any insight :)

**Comment by oddlama** [comment]
I'm not quite sure whether you are asking for something specific that you are actually able to represent manually with `kanidm` CLI commands, or whether you are unsure how to integrate netbird and kanidm properly. The latter case would be unrelated to this tool and you might want to ask on kanidm's matrix channel.

The netbird stuff reads to me as if you would need to do a group claim map to get what you want, but I haven't tried that. I guess the kanidm / netbird folks may be able to help you in that case.

**Comment by mannp** [comment]
Not the latter, I have netbird and kanidm hooked up.

I have actually put a query with kanidm, as I am not sure it can do what I am trying, so was alittle premature asking here.

Will close this.
