### ISSUE TITLE
Add support for multiple redirect url?

### ISSUE THREAD

**Issue by xinyangli** [oddlama/kanidm-provision#7]
Hi @oddlama,

Upstream started to support multiple redirect url in v1.3.0 https://github.com/kanidm/kanidm/issues/2433. I wonder if it's a easy update to integrate this into kanidm-provision?

**Comment by oddlama** [comment]
Thanks for the heads-up, this shouldn't be relatively easy to add. To keep the old `state.json` backwards compatible I'd have to check whether serde supports some kind of `Either` type to allow a single value or an array to be passed. Other than that the API request changes should be minimal.

**Comment by xinyangli** [comment]
Thanks for your reply! 

A quick lookup shows that we might be able to implement that with an [untagged enum representation](https://serde.rs/enum-representations.html) in serde.

Btw, this is what nix is good at 🤣

**Comment by oddlama** [comment]
Done, upgrading this upstream into nixpkgs will probably take a few days until it reaches nixpkgs-unstable

**Comment by xinyangli** [comment]
Thanks, that's a quick update!! 🎉
